// Sidebar
export const SIDEBAR_VISIBILITY_TOGGLE = "SIDEBAR_VISIBILITY_TOGGLE";
export const SIDEBAR_VISIBILITY_SHOW = "SIDEBAR_VISIBILITY_SHOW";
export const SIDEBAR_VISIBILITY_HIDE = "SIDEBAR_VISIBILITY_HIDE";
export const SIDEBAR_STICKY_TOGGLE = "SIDEBAR_STICKY_TOGGLE";
export const SIDEBAR_STICKY_ENABLE = "SIDEBAR_STICKY_ENABLE";
export const SIDEBAR_STICKY_DISABLE = "SIDEBAR_STICKY_DISABLE";

// Layout
export const LAYOUT_BOXED_TOGGLE = "LAYOUT_BOXED_TOGGLE";
export const LAYOUT_BOXED_ENABLE = "LAYOUT_BOXED_ENABLE";
export const LAYOUT_BOXED_DISABLE = "LAYOUT_BOXED_DISABLE";


// Theme
export const THEME_TOGGLE = "THEME_TOGGLE";


//Pitch Designer 
export const ADD_PITCH_PREVIEW_ON_THE_MAP = "ADD_PITCH_PREVIEW_ON_THE_MAP";
export const HANDLE_MAP_ZOOM_AND_CENTER = "HANDLE_MAP_ZOOM_AND_CENTER";
export const TOGGLE_PITCH_CREATOR_STEP = "TOGGLE_PITCH_CREATOR_STEP";
export const ROTATE_PITCH = "ROTATE_PITCH";
export const SUBMIT_ROTATE_STAGE = "SUBMIT_ROTATE_STAGE";
export const ADD_MORE_PITCH = "ADD_MORE_PITCH";
export const REMOVE_PITCH = "REMOVE_PITCH";
export const SAVE_LAYOUT = "SAVE_LAYOUT";
export const GET_LAYOUT_NAME_AND_MARKET_NAME_FROM_SERVER = "GET_LAYOUT_NAME_AND_MARKET_NAME_FROM_SERVER";
export const CHECK_LAYOUT_NAME_CONFLICT = "CHECK_LAYOUT_NAME_CONFLICT";
export const GET_DISABLE_MARKET_DATES = "GET_DISABLE_MARKET_DATES";
export const DELETE_LAYOUT = "DELETE_LAYOUT";
export const DELETE_LAYOUT_SUCCESS = "DELETE_LAYOUT_SUCCESS";
export const START_EDIT_LAYOUT = "START_EDIT_LAYOUT";
export const EDIT_LAYOUT = "EDIT_LAYOUT";
export const DELETE_PITCH = "DELETE_PITCH";
export const SAVE_PITCH_ASYNC = "SAVE_PITCH_ASYNC";


//Common
export const SAVE_BROWSER_HISTORY = "SAVE_BROWSER_HISTORY";
export const GET_CURRENT_LOCATION_SUCCESS = "GET_CURRENT_LOCATION";
export const GET_CURRENT_LOCATION_FAILED = "GET_CURRENT_LOCATION_FAILED";


//Pitch Planner
export const PICK_MARKET_DATE = "PICK_MARKET_DATE";
export const CHOOSE_MARKET_DATE = "CHOOSE_MARKET_DATE";
export const LOAD_RELATED_LAYOUT = "LOAD_RELATED_LAYOUT";
export const UPDATE_PITCH_INFO_TABLE = "UPDATE_PITCH_INFO_TABLE";
export const LOAD_USERS = "LOAD_USERS";
export const SAVE_MARKET = "SAVE_MARKET";
export const CHANGE_CALENDAR_MONTH_HANDLER = "CHANGE_CALENDAR_MONTH_HANDLER";
export const GET_INDIVISUAL_MARKET_FROM_SERVER = "GET_INDIVISUAL_MARKET_FROM_SERVER";
export const DELETE_PITCH_FROM_MARKET = "DELETE_PITCH_FROM_MARKET";
export const CHANGE_MARKET_DATE_ASYNC = "CHANGE_MARKET_DATE_ASYNC";
export const GET_MARKET_DISABLE_DATES_IN_MARKET_EDIT_PAGE = "GET_MARKET_DISABLE_DATES_IN_MARKET_EDIT_PAGE";
export const EDIT_MARKET = "EDIT_MARKET";
export const DELETE_MARKET = "DELETE_MARKET";
export const UPDATE_PITCH_TABLE_IN_EDIT_MARKET_PAGE = "UPDATE_PITCH_TABLE_IN_EDIT_MARKET_PAGE";
export const HANDLE_MAP_ZOOM_ON_MARKET_EDIT_PAGE = "HANDLE_MAP_ZOOM_ON_MARKET_EDIT_PAGE";
export const LOAD_RELATED_TRADER_INFO_CARD = "LOAD_RELATED_TRADER_INFO_CARD";

//Home
export const GET_MARKETS_FROM_SERVER = "GET_MARKETS_FROM_SERVER";

//Traders
export const GET_TRADERS_LIST = "GET_TRADERS_LIST";

//PriceTypes
export const GET_PRICETYPES_LIST = "GET_PRICETYPES_LIST";
export const REMOVE_PRICE_TYPE = "REMOVE_PRICE_TYPE";
export const TOGGLE_PRICE_TYPE_MODAL = "TOGGLE_PRICE_TYPE_MODAL";

//Companies
export const GET_COMPANIES_LIST = "GET_COMPANIES_LIST";
export const LOAD_RELATED_COMPANY_INFO_CARD = "LOAD_RELATED_COMPANY_INFO_CARD";
export const REMOVE_COMPANY = "REMOVE_COMPANY";
export const START_ADD_COMPANY = "START_ADD_COMPANY";
export const ADD_COMPANY = "ADD_COMPANY";
export const START_COMPANY_MODAL = "START_COMPANY_MODAL";
export const EDIT_COMPANY = "EDIT_COMPANY";
export const CLEAR_COMPANIES = "CLEAR_COMPANIES";
export const TOGGLE_COMPANY_MODAL = "TOGGLE_COMPANY_MODALE";

//Projects
export const GET_PROJECTS_LIST = "GET_PROJECTS_LIST";
export const LOAD_RELATED_PROJECT_INFO_CARD = "LOAD_RELATED_PROJECT_INFO_CARD";
export const REMOVE_PROJECT = "REMOVE_PROJECT";
export const START_ADD_PROJECT = "START_ADD_PROJECT";
export const ADD_PROJECT = "ADD_PROJECT";
export const START_PROJECT_MODAL = "START_PROJECT_MODAL";
export const EDIT_PROJECT = "EDIT_PROJECT";
export const CLEAR_PROJECTS = "CLEAR_PROJECTS";
export const TOGGLE_PROJECT_MODAL = "TOGGLE_PROJECT_MODAL";

//Departments
export const GET_DEPARTMENTS_LIST = "GET_DEPARTMENTS_LIST";
export const LOAD_RELATED_DEPARTMENT_INFO_CARD = "LOAD_RELATED_DEPARTMENT_INFO_CARD";
export const REMOVE_DEPARTMENT = "REMOVE_DEPARTMENT";
export const START_ADD_DEPARTMENT = "START_ADD_DEPARTMENT";
export const ADD_DEPARTMENT = "ADD_DEPARTMENT";
export const START_DEPARTMENT_MODAL = "START_DEPARTMENT_MODAL";
export const EDIT_DEPARTMENT = "EDIT_DEPARTMENT";
export const CLEAR_DEPARTMENTS = "CLEAR_DEPARTMENTS";
export const TOGGLE_DEPARTMENT_MODAL = "TOGGLE_DEPARTMENT_MODAL";

//JobPositions
export const GET_JOBPOSITIONS_LIST = "GET_JOBPOSITIONS_LIST";
export const LOAD_RELATED_JOBPOSITION_INFO_CARD = "LOAD_RELATED_JOBPOSITION_INFO_CARD";
export const REMOVE_JOBPOSITION = "REMOVE_JOBPOSITION";
export const START_ADD_JOBPOSITION = "START_ADD_JOBPOSITION";
export const ADD_JOBPOSITION = "ADD_JOBPOSITION";
export const START_JOBPOSITION_MODAL = "START_JOBPOSITION_MODAL";
export const EDIT_JOBPOSITION = "EDIT_JOBPOSITION";
export const CLEAR_JOBPOSITIONS = "CLEAR_JOBPOSITIONS";
export const TOGGLE_JOBPOSITION_MODAL = "TOGGLE_JOBPOSITION_MODAL";

//Employees
export const GET_EMPLOYEES_LIST = "GET_EMPLOYEES_LIST";
export const GET_EMPLOYEE_CODES_LIST = "GET_EMPLOYEE_CODES_LIST";
export const LOAD_RELATED_EMPLOYEE_INFO_CARD = "LOAD_RELATED_EMPLOYEE_INFO_CARD";
export const REMOVE_EMPLOYEE = "REMOVE_EMPLOYEE";
export const START_ADD_EMPLOYEE = "START_ADD_EMPLOYEE";
export const ADD_EMPLOYEE = "ADD_EMPLOYEE";
export const START_EMPLOYEE_MODAL = "START_EMPLOYEE_MODAL";
export const EDIT_EMPLOYEE = "EDIT_EMPLOYEE";
export const CLEAR_EMPLOYEES = "CLEAR_EMPLOYEES";
export const TOGGLE_EMPLOYEE_MODAL = "TOGGLE_EMPLOYEE_MODAL";

//Users
export const GET_USERS_LIST = "GET_USERS_LIST";
export const LOAD_RELATED_USER_INFO_CARD = "LOAD_RELATED_USER_INFO_CARD";
export const REMOVE_USER = "REMOVE_USER";
export const START_ADD_USER = "START_ADD_USER";
export const ADD_USER = "ADD_USER";
export const START_USER_MODAL = "START_USER_MODAL";
export const EDIT_USER = "EDIT_USER";
export const CLEAR_USERS = "CLEAR_USERS";
export const TOGGLE_USER_MODAL = "TOGGLE_USER_MODAL";

//DoctorTypes
export const GET_DOCTORTYPES_LIST = "GET_DOCTORTYPES_LIST";
export const LOAD_RELATED_DOCTORTYPE_INFO_CARD = "LOAD_RELATED_DOCTORTYPE_INFO_CARD";
export const REMOVE_DOCTORTYPE = "REMOVE_DOCTORTYPE";
export const START_ADD_DOCTORTYPE = "START_ADD_DOCTORTYPE";
export const ADD_DOCTORTYPE = "ADD_DOCTORTYPE";
export const START_DOCTORTYPE_MODAL = "START_DOCTORTYPE_MODAL";
export const EDIT_DOCTORTYPE = "EDIT_DOCTORTYPE";
export const CLEAR_DOCTORTYPES = "CLEAR_DOCTORTYPES";
export const TOGGLE_DOCTORTYPE_MODAL = "TOGGLE_DOCTORTYPE_MODAL";

//Doctors
export const GET_DOCTORS_LIST = "GET_DOCTORS_LIST";
export const LOAD_RELATED_DOCTOR_INFO_CARD = "LOAD_RELATED_DOCTOR_INFO_CARD";
export const REMOVE_DOCTOR = "REMOVE_DOCTOR";
export const START_ADD_DOCTOR = "START_ADD_DOCTOR";
export const ADD_DOCTOR = "ADD_DOCTOR";
export const START_DOCTOR_MODAL = "START_DOCTOR_MODAL";
export const EDIT_DOCTOR = "EDIT_DOCTOR";
export const CLEAR_DOCTORS = "CLEAR_DOCTORS";
export const TOGGLE_DOCTOR_MODAL = "TOGGLE_DOCTOR_MODAL";

//SurveyTypes
export const GET_SURVEYTYPES_LIST = "GET_SURVEYTYPES_LIST";
export const LOAD_RELATED_SURVEYTYPE_INFO_CARD = "LOAD_RELATED_SURVEYTYPE_INFO_CARD";
export const REMOVE_SURVEYTYPE = "REMOVE_SURVEYTYPE";
export const START_ADD_SURVEYTYPE = "START_ADD_SURVEYTYPE";
export const ADD_SURVEYTYPE = "ADD_SURVEYTYPE";
export const START_SURVEYTYPE_MODAL = "START_SURVEYTYPE_MODAL";
export const EDIT_SURVEYTYPE = "EDIT_SURVEYTYPE";
export const CLEAR_SURVEYTYPES = "CLEAR_SURVEYTYPES";
export const TOGGLE_SURVEY_TYPE_MODAL = "TOGGLE_SURVEY_TYPE_MODAL";

//Notifications
export const GET_NOTIFICATIONS_LIST = "GET_NOTIFICATIONS_LIST";
export const GET_FILTERED_NOTIFICATIONS_LIST = "GET_FILTERED_NOTIFICATIONS_LIST";
export const REMOVE_NOTIFICATION = "REMOVE_NOTIFICATION";
export const START_ADD_NOTIFICATION = "START_ADD_NOTIFICATION";
export const ADD_NOTIFICATION = "ADD_NOTIFICATION";
export const START_NOTIFICATION_MODAL = "START_NOTIFICATION_MODAL";
export const EDIT_NOTIFICATION = "EDIT_NOTIFICATION";
export const CLEAR_NOTIFICATIONS = "CLEAR_NOTIFICATIONS";
export const TOGGLE_NOTIFICATION_MODAL = "TOGGLE_NOTIFICATION_MODAL";

//PersonelMealDay
export const GET_PERSONELMEALDAYSEx_LIST = "GET_PERSONELMEALDAYSEx_LIST";
export const GET_PERSONELMEALONEDAYS_LIST = "GET_PERSONELMEALONEDAYS_LIST";
export const GET_PERSONELMEALDAYS_LIST = "GET_PERSONELMEALDAYS_LIST";
export const GET_SERVEDMEALS_LIST = "GET_SERVEDMEALS_LIST";
export const LOAD_RELATED_PERSONELMEALDAY_INFO_CARD = "LOAD_RELATED_PERSONELMEALDAY_INFO_CARD";
export const REMOVE_PERSONELMEALDAY = "REMOVE_PERSONELMEALDAY";
export const START_ADD_PERSONELMEALDAY = "START_ADD_PERSONELMEALDAY";
export const ADD_PERSONELMEALDAY = "ADD_PERSONELMEALDAY";
export const START_PERSONELMEALDAY_MODAL = "START_PERSONELMEALDAY_MODAL";
export const EDIT_PERSONELMEALDAY = "EDIT_PERSONELMEALDAY";
export const CLEAR_PERSONELMEALDAYS = "CLEAR_PERSONELMEALDAYS";
export const TOGGLE_PERSONELMEALDAY_MODAL = "TOGGLE_PERSONELMEALDAY_MODAL";

//GuestMealDay
export const GET_GUESTMEALDAYSEx_LIST = "GET_GUESTMEALDAYSEx_LIST";
export const GET_GUESTMEALONEDAYS_LIST = "GET_GUESTMEALONEDAYS_LIST";
export const GET_GUESTMEALSDAY_LIST = "GET_GUESTMEALSDAY_LIST";
export const GET_GUEST_MEALSDAY_QTY = "GET_GUEST_MEALSDAY_QTY";
export const LOAD_RELATED_GUESTMEALDAY_INFO_CARD = "LOAD_RELATED_GUESTMEALDAY_INFO_CARD";
export const REMOVE_GUESTMEALDAY = "REMOVE_GUESTMEALDAY";
export const START_ADD_GUESTMEALDAY = "START_ADD_GUESTMEALDAY";
export const ADD_GUESTMEALDAY = "ADD_GUESTMEALDAY";
export const START_GUESTMEALDAY_MODAL = "START_GUESTMEALDAY_MODAL";
export const EDIT_GUESTMEALDAY = "EDIT_GUESTMEALDAY";
export const EDIT_GUESTMEALDAYJUNCTION = "EDIT_GUESTMEALDAYJUNCTION";
export const CLEAR_GUESTMEALDAYS = "CLEAR_GUESTMEALDAYS";
export const TOGGLE_GUESTMEALDAY_MODAL = "TOGGLE_GUESTMEALDAY_MODAL";

//MealDay
export const GET_MEALDAYS_LIST = "GET_MEALDAYS_LIST";
export const GET_MEALSDAY_LIST = "GET_MEALSDAY_LIST";
export const LOAD_RELATED_MEALDAY_INFO_CARD = "LOAD_RELATED_MEALDAY_INFO_CARD";
export const REMOVE_MEALDAY = "REMOVE_MEALDAY";
export const START_ADD_MEALDAY = "START_ADD_MEALDAY";
export const ADD_MEALDAY = "ADD_MEALDAY";
export const START_MEALDAY_MODAL = "START_MEALDAY_MODAL";
export const EDIT_MEALDAY = "EDIT_MEALDAY";
export const CLEAR_MEALDAYS = "CLEAR_MEALDAYS";
export const TOGGLE_MEALDAY_MODAL = "TOGGLE_MEALDAY_MODAL";
export const GET_CURRENTMONTHDATES = "GET_CURRENTMONTHDATES";

//Meal 
export const GET_MEALS_LIST = "GET_MEALS_LIST";
export const LOAD_RELATED_MEAL_INFO_CARD = "LOAD_RELATED_MEAL_INFO_CARD";
export const REMOVE_MEAL = "REMOVE_MEAL";
export const START_ADD_MEAL = "START_ADD_MEAL";
export const ADD_MEAL = "ADD_MEAL";
export const START_MEAL_MODAL = "START_MEAL_MODAL";
export const EDIT_MEAL = "EDIT_MEAL";
export const CLEAR_MEALS = "CLEAR_MEALS";
export const TOGGLE_MEAL_MODAL = "TOGGLE_MEAL_MODAL";

//Surveys
export const GET_SURVEYS_LIST = "GET_SURVEYS_LIST";
export const GET_USED_SURVEYS_LIST = "GET_USED_SURVEYS_LIST";
export const GET_UNUSED_SURVEYS_LIST = "GET_UNUSED_SURVEYS_LIST";
export const LOAD_RELATED_SURVEY_INFO_CARD = "LOAD_RELATED_SURVEY_INFO_CARD";
export const REMOVE_SURVEY = "REMOVE_SURVEY";
export const START_ADD_SURVEY = "START_ADD_SURVEY";
export const ADD_SURVEY = "ADD_SURVEY";
export const START_SURVEY_MODAL = "START_SURVEY_MODAL";
export const EDIT_SURVEY = "EDIT_SURVEY";
export const CLEAR_SURVEYS = "CLEAR_SURVEYS";
export const TOGGLE_SURVEY_MODAL = "TOGGLE_SURVEY_MODAL";

//SurveyDepartment
export const GET_SURVEYDEPARTMENTS_LIST = "GET_SURVEYDEPARTMENTS_LIST";
export const LOAD_RELATED_SURVEYDEPARTMENT_INFO_CARD = "LOAD_RELATED_SURVEYDEPARTMENT_INFO_CARD";
export const REMOVE_SURVEYDEPARTMENT = "REMOVE_SURVEYDEPARTMENT";
export const START_ADD_SURVEYDEPARTMENT = "START_ADD_SURVEYDEPARTMENT";
export const ADD_SURVEYDEPARTMENT = "ADD_SURVEYDEPARTMENT";
export const START_SURVEYDEPARTMENT_MODAL = "START_SURVEYDEPARTMENT_MODAL";
export const EDIT_SURVEYDEPARTMENT = "EDIT_SURVEYDEPARTMENT";
export const CLEAR_SURVEYDEPARTMENTS = "CLEAR_SURVEYDEPARTMENTS";
export const TOGGLE_SURVEYDEPARTMENT_MODAL = "TOGGLE_SURVEYDEPARTMENT_MODAL";

//OptionalQuestions
export const GET_OPTIONALQUESTIONS_LIST = "GET_OPTIONALQUESTIONS_LIST";
export const GET_OPTIONALQUESTION = "GET_OPTIONALQUESTION";
export const REMOVE_OPTIONALQUESTION = "REMOVE_OPTIONALQUESTION";
export const ADD_OPTIONALQUESTION = "ADD_OPTIONALQUESTION";
export const EDIT_OPTIONALQUESTION = "EDIT_OPTIONALQUESTION";
export const CLEAR_OPTIONALQUESTIONS = "CLEAR_OPTIONALQUESTIONS";

export const GET_OPTIONALQUESTIONSANSWER_LIST = "GET_OPTIONALQUESTIONSANSWER_LIST";
export const GET_OPTIONALQUESTIONANSWER = "GET_OPTIONALQUESTIONANSWER";
export const REMOVE_OPTIONALQUESTIONANSWER = "REMOVE_OPTIONALQUESTIONANSWER";
export const ADD_OPTIONALQUESTIONANSWER = "ADD_OPTIONALQUESTIONANSWER";
export const EDIT_OPTIONALQUESTIONANSWER = "EDIT_OPTIONALQUESTIONANSWER";
export const CLEAR_OPTIONALQUESTIONSANSWER = "CLEAR_OPTIONALQUESTIONSANSWER";

//UserAnswers
export const ADD_USERANSWERS = "ADD_USERANSWERS";
export const GET_USERANSWERS_LIST = "GET_USERANSWERS_LIST";
export const GET_USERANSWER = "GET_USERANSWER";
export const CLEAR_USERANSWERS = "CLEAR_USERANSWERS";

//SurveyReport
export const ADD_SURVEYREPORT = "ADD_SURVEYREPORT";
export const GET_SURVEYREPORT_LIST = "GET_SURVEYREPORT_LIST";
export const EDIT_SURVEYREPORT = "EDIT_SURVEYREPORT";
export const REMOVE_SURVEYREPORT = "REMOVE_SURVEYREPORT";

//DOCSCHEDULEWEEKLYDAYS
export const GET_DOCSCHEDULEWEEKLYDAYS_LIST = "GET_DOCSCHEDULEWEEKLYDAYS_LIST";
export const LOAD_RELATED_DOCSCHEDULEWEEKLYDAY_INFO_CARD = "LOAD_RELATED_DOCSCHEDULEWEEKLYDAY_INFO_CARD";
export const REMOVE_DOCSCHEDULEWEEKLYDAY = "REMOVE_DOCSCHEDULEWEEKLYDAY";
export const ADD_DOCSCHEDULEWEEKLYDAY = "ADD_DOCSCHEDULEWEEKLYDAY";
export const EDIT_DOCSCHEDULEWEEKLYDAY = "EDIT_DOCSCHEDULEWEEKLYDAY";
export const CLEAR_DOCSCHEDULEWEEKLYDAYS = "CLEAR_DOCSCHEDULEWEEKLYDAYS";

//DOCSCHEDULEDAYS
export const GET_DOCSCHEDULEDAYS_LIST = "GET_DOCSCHEDULEDAYS_LIST";
export const LOAD_RELATED_DOCSCHEDULEDAY_INFO_CARD = "LOAD_RELATED_DOCSCHEDULEDAY_INFO_CARD";
export const REMOVE_DOCSCHEDULEDAY = "REMOVE_DOCSCHEDULEDAY";
export const ADD_DOCSCHEDULEDAY = "ADD_DOCSCHEDULEDAY";
export const EDIT_DOCSCHEDULEDAY = "EDIT_DOCSCHEDULEDAY";
export const CLEAR_DOCSCHEDULEDAYS = "CLEAR_DOCSCHEDULEDAYS";

//DOCAPPOINTMENTS
export const GET_DOCAPPOINTMENTTIMES_LIST = "GET_DOCAPPOINTMENTTIMES_LIST";
export const GET_DOCAPPOINTMENTS_LIST = "GET_DOCAPPOINTMENTS_LIST";
export const START_DOCAPPOINTMENT_MODAL = "START_DOCAPPOINTMENT_MODAL";
export const START_ADD_DOCAPPOINTMENT = "START_ADD_DOCAPPOINTMENT";
export const SET_DOCAPPOINTMENT_SCHEDULEDAYID = "SET_DOCAPPOINTMENT_SCHEDULEDAYID";
export const SET_DOCAPPOINTMENT_DOCTORID = "SET_DOCAPPOINTMENT_DOCTORID";
export const LOAD_RELATED_DOCAPPOINTMENT_INFO_CARD = "LOAD_RELATED_DOCAPPOINTMENT_INFO_CARD";
export const REMOVE_DOCAPPOINTMENT = "REMOVE_DOCAPPOINTMENT";
export const ADD_DOCAPPOINTMENT = "ADD_DOCAPPOINTMENT";
export const EDIT_DOCAPPOINTMENT = "EDIT_DOCAPPOINTMENT";
export const TOGGLE_DOCAPPOINTMENT_MODAL = "TOGGLE_DOCAPPOINTMENT_MODAL";
export const CLEAR_DOCAPPOINTMENTS = "CLEAR_DOCAPPOINTMENTS";

//PATIENTSFILES
export const GET_PATIENTSFILES_LIST = "GET_PATIENTSFILES_LIST";
export const LOAD_RELATED_PATIENTFILE_INFO_CARD = "LOAD_RELATED_PATIENTFILE_INFO_CARD";
export const REMOVE_PATIENTFILE = "REMOVE_PATIENTFILE";
export const ADD_PATIENTFILE = "ADD_PATIENTFILE";
export const EDIT_PATIENTFILE = "EDIT_PATIENTFILE";
export const CLEAR_PATIENTSFILES = "CLEAR_PATIENTSFILES";

//Auth
export const AUTH_START = "AUTH_START";
export const USER_REGISTER = "USER_REGISTER";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const USERNAME_PASSWORD_CHANGE = "USERNAME_PASSWORD_CHANGE";
export const LOG_OUT = "LOG_OUT";

//Group
export const GET_GROUPS_LIST = "GET_GROUPS_LIST";
export const LOAD_RELATED_GROUP_INFO_CARD = "LOAD_RELATED_GROUP_INFO_CARD";
export const REMOVE_GROUP = "REMOVE_GROUP";
export const START_ADD_GROUP = "START_ADD_GROUP";
export const ADD_GROUP = "ADD_GROUP";
export const START_GROUP_MODAL = "START_GROUP_MODAL";
export const EDIT_GROUP = "EDIT_GROUP";
export const CLEAR_GROUPS = "CLEAR_GROUPS";
export const TOGGLE_GROUP_MODAL = "TOGGLE_GROUP_TYPE_MODAL";

//Permission
export const GET_PERMISSIONS_LIST = "GET_PERMISSIONS_LIST";
export const GET_CONTENTTYPES_LIST = "GET_CONTENTTYPES_LIST";
export const LOAD_RELATED_PERMISSION_INFO_CARD = "LOAD_RELATED_PERMISSION_INFO_CARD";
export const REMOVE_PERMISSION = "REMOVE_PERMISSION";
export const START_ADD_PERMISSION = "START_ADD_PERMISSION";
export const ADD_PERMISSION = "ADD_PERMISSION";
export const START_PERMISSION_MODAL = "START_PERMISSION_MODAL";
export const EDIT_PERMISSION = "EDIT_PERMISSION";
export const CLEAR_PERMISSIONS = "CLEAR_PERMISSIONS";
export const TOGGLE_PERMISSION_MODAL = "TOGGLE_PERMISSION_TYPE_MODAL";

//User Group
export const GET_USERGROUPS_LIST = "GET_USERGROUPS_LIST";
export const ADD_USERGROUP = "ADD_USERGROUP";
export const EDIT_USERGROUP = "EDIT_USERGROUP"
export const REMOVE_USERGROUP = "REMOVE_USERGROUP";

//User Permission
export const GET_USERPERMISSIONS_LIST = "GET_USERPERMISSIONS_LIST";
export const ADD_USERPERMISSION = "ADD_USERPERMISSION";
export const EDIT_USERPERMISSION = "EDIT_USERPERMISSION"
export const REMOVE_USERPERMISSION = "REMOVE_USERPERMISSION";

//Group Permission
export const GET_GROUPPERMISSIONS_LIST = "GET_GROUPPERMISSIONS_LIST";
export const ADD_GROUPPERMISSION = "ADD_GROUPPERMISSION";
export const EDIT_GROUPPERMISSION = "EDIT_GROUPPERMISSION"
export const REMOVE_GROUPPERMISSION = "REMOVE_GROUPPERMISSION";

//Alert
export const TOGGLE_ALERT_MODAL = "TOGGLE_ALERT_MODAL";
export const OPEN_ALERT_MODAL = "OPEN_ALERT_MODAL";

//CaterTypes
export const GET_CATERTYPES_LIST = "GET_CATERTYPES_LIST";
export const GET_REQUESTCATERTYPES_LIST = "GET_REQUESTCATERTYPE_LIST";
export const LOAD_RELATED_CATERTYPE_INFO_CARD = "LOAD_RELATED_CATERTYPE_INFO_CARD";
export const REMOVE_CATERTYPE = "REMOVE_CATERTYPE";
export const START_ADD_CATERTYPE = "START_ADD_CATERTYPE";
export const ADD_CATERTYPE = "ADD_CATERTYPE";
export const START_CATERTYPE_MODAL = "START_CATERTYPE_MODAL";
export const EDIT_CATERTYPE = "EDIT_CATERTYPE";
export const EDIT_REQUESTCATERTYPE = "EDIT_REQUESTCATERTYPE";
export const CLEAR_CATERTYPES = "CLEAR_CATERTYPES";
export const TOGGLE_CATERTYPE_MODAL = "TOGGLE_CATERTYPE_MODALE";

//ROOMTYPE
export const GET_ROOMTYPES_LIST = "GET_ROOMTYPES_LIST";
export const GET_REQUESTROOMTYPES_LIST = "GET_REQUESTROOMTYPE_LIST";
export const LOAD_RELATED_ROOMTYPE_INFO_CARD = "LOAD_RELATED_ROOMTYPE_INFO_CARD";
export const REMOVE_ROOMTYPE = "REMOVE_ROOMTYPE";
export const START_ADD_ROOMTYPE = "START_ADD_ROOMTYPE";
export const ADD_ROOMTYPE = "ADD_ROOMTYPE";
export const START_ROOMTYPE_MODAL = "START_ROOMTYPE_MODAL";
export const EDIT_ROOMTYPE = "EDIT_ROOMTYPE";
export const EDIT_REQUESTROOMTYPE = "EDIT_REQUESTROOMTYPE";
export const CLEAR_ROOMTYPES = "CLEAR_ROOMTYPES";
export const TOGGLE_ROOMTYPE_MODAL = "TOGGLE_ROOMTYPE_MODALE";

//Equipments
export const GET_EQUIPMENTS_LIST = "GET_EQUIPMENTS_LIST";
export const LOAD_RELATED_EQUIPMENT_INFO_CARD = "LOAD_RELATED_EQUIPMENT_INFO_CARD";
export const REMOVE_EQUIPMENT = "REMOVE_EQUIPMENT";
export const START_ADD_EQUIPMENT = "START_ADD_EQUIPMENT";
export const ADD_EQUIPMENT = "ADD_EQUIPMENT";
export const START_EQUIPMENT_MODAL = "START_EQUIPMENT_MODAL";
export const EDIT_EQUIPMENT = "EDIT_EQUIPMENT";
export const CLEAR_EQUIPMENTS = "CLEAR_EQUIPMENTS";
export const TOGGLE_EQUIPMENT_MODAL = "TOGGLE_EQUIPMENT_MODALE";

//Rooms
export const GET_ROOMS_LIST = "GET_ROOMS_LIST";
export const LOAD_RELATED_ROOM_INFO_CARD = "LOAD_RELATED_ROOM_INFO_CARD";
export const REMOVE_ROOM = "REMOVE_ROOM";
export const START_ADD_ROOM = "START_ADD_ROOM";
export const ADD_ROOM = "ADD_ROOM";
export const START_ROOM_MODAL = "START_ROOM_MODAL";
export const EDIT_ROOM = "EDIT_ROOM";
export const CLEAR_ROOMS = "CLEAR_ROOMS";
export const TOGGLE_ROOM_MODAL = "TOGGLE_ROOM_MODALE";

//Rerquests
export const GET_REQUESTS_LIST = "GET_REQUESTS_LIST";
export const GET_DATEREQUESTS_LIST = "GET_DATEREQUESTS_LIST";
export const GET_DATEREQUESTCATERTYPES_LIST = "GET_DATEREQUESTCATERTYPES_LIST";
export const LOAD_RELATED_REQUEST_INFO_CARD = "LOAD_RELATED_REQUEST_INFO_CARD";
export const REMOVE_REQUEST = "REMOVE_REQUEST";
export const START_ADD_REQUEST = "START_ADD_REQUEST";
export const ADD_REQUEST = "ADD_REQUEST";
export const START_REQUEST_MODAL = "START_REQUEST_MODAL";
export const EDIT_REQUEST = "EDIT_REQUEST";
export const CLEAR_REQUESTS = "CLEAR_REQUESTS";
export const TOGGLE_REQUEST_MODAL = "TOGGLE_REQUEST_MODALE";